# Generated by Django 6.0 on 2026-01-01 00:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ble_beacon_id', models.CharField(max_length=100, unique=True)),
                ('location_name', models.CharField(max_length=200)),
                ('gps_coordinates', models.JSONField()),
                ('install_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dispensers',
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='DispenserProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('current_inventory', models.IntegerField(default=0)),
                ('max_capacity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='dispensers.dispenser')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenser_products', to='products.product')),
            ],
            options={
                'db_table': 'dispenser_products',
                'ordering': ['dispenser', 'row_number'],
                'unique_together': {('dispenser', 'row_number')},
            },
        ),
    ]
