# Generated by Django 4.2.7 on 2026-01-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dispensers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dispenser",
            old_name="id",
            new_name="dispenser_id",
        ),
    ]
