# Generated by Django 4.2.7 on 2026-01-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic (Free Napkins)"),
                    ("premium", "Premium (Paid)"),
                    ("corporate", "Corporate Plan"),
                    ("none", "No Subscription"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
    ]
