# Generated by Django 6.0 on 2026-01-01 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['level'], name='logs_level_de2b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['action'], name='logs_action_68aa90_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['timestamp'], name='logs_timesta_e5126f_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', 'timestamp'], name='logs_user_id_2f2997_idx'),
        ),
    ]
